### ISSUE TITLE
Receiving AccessDenied on Nerdgraph request

### ISSUE THREAD

**Issue by jrhinehart** [newrelic/nr1-integrations-manager#35]
Logs with redactions below, nri-sync seems to start well, but receives an AccessDenied Error on Nerdgraph requests

Startup for nri-sync
```
time="2020-09-16T18:13:56Z" level=debug msg="running task" component=integrations.Definition integration_name=nri-sync
time="2020-09-16T18:13:56Z" level=debug msg="running through all discovery matches" component=integrations.Definition integration_name=nri-sync
time="2020-09-16T18:13:56Z" level=debug msg="found a nil ConfigTemplate" component=integrations.Definition integration_name=nri-sync
time="2020-09-16T18:13:56Z" level=debug msg="executing task" component=integrations.Definition integration_name=nri-sync
time="2020-09-16T18:13:56Z" level=debug msg="waiting while the integration instances run" component=integrations.runner.Group integration_name=nri-sync
time="2020-09-16T18:13:56Z" level=debug msg="running command" command=/var/db/newrelic-infra/newrelic-integrations/bin/nri-sync component=integrations.Executor env="[LANG=en_US.UTF-8 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket NR_UUID=XXXXXXXX NR_ACCOUNT_ID=XXXXXX NR_COLLECTION=XXXXXX NR_API_KEY=<HIDDEN> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin VERBOSE=1]" path=/var/db/newrelic-infra/newrelic-integrations/bin/nri-sync
time="2020-09-16T18:13:56Z" level=debug msg="[2020-09-16T18:13:56Z INFO  nri_sync::nrsync] starting nri-sync v:1.0.0" component=integrations.runner.Group integration_name=nri-sync
time="2020-09-16T18:13:56Z" level=debug msg="[2020-09-16T18:13:56Z INFO  nri_sync::nrsync] collecting files on disk: /etc/newrelic-infra/integrations.d" component=integrations.runner.Group integration_name=nri-sync
time="2020-09-16T18:13:56Z" level=debug msg="[2020-09-16T18:13:56Z INFO  nri_sync::nrsync] fetching collection: XXXXXXXXXX" component=integrations.runner.Group integration_name=nri-sync
time="2020-09-16T18:13:56Z" level=debug msg="[2020-09-16T18:13:56Z DEBUG rustls::anchors] add_pem_file processed 140 valid and 0 invalid certs" component=integrations.runner.Group integration_name=nri-sync
time="2020-09-16T18:13:56Z" level=debug msg="[2020-09-16T18:13:56Z DEBUG hyper::client::connect::dns] resolving host=\"api.newrelic.com\" " component=integrations.runner.Group integration_name=nri-sync
time="2020-09-16T18:13:56Z" level=debug msg="[2020-09-16T18:13:56Z DEBUG hyper::client::connect::http] connecting to 162.247.242.11:443 " component=integrations.runner.Group integration_name=nri-sync
time="2020-09-16T18:13:56Z" level=debug msg="[2020-09-16T18:13:56Z DEBUG hyper::client::connect::http] connected to 162.247.242.11:443 " component=integrations.runner.Group integration_name=nri-sync
time="2020-09-16T18:13:56Z" level=debug msg="[2020-09-16T18:13:56Z DEBUG rustls::client::hs] No cached session for DNSNameRef(\"api.newrelic.com\")" component=integrations.runner.Group integration_name=nri-sync
time="2020-09-16T18:13:56Z" level=debug msg="[2020-09-16T18:13:56Z DEBUG rustls::client::hs] Not resuming any session" component=integrations.runner.Group integration_name=nri-sync
```

-------

Error
```
time="2020-09-16T18:13:56Z" level=debug msg="[2020-09-16T18:13:56Z ERROR rustls::session] TLS alert received: Message {" component=integrations.runner.Group integration_name=nri-sync
time="2020-09-16T18:13:56Z" level=debug msg="        typ: Alert," component=integrations.runner.Group integration_name=nri-sync
time="2020-09-16T18:13:56Z" level=debug msg="        version: TLSv1_0," component=integrations.runner.Group integration_name=nri-sync
time="2020-09-16T18:13:56Z" level=debug msg="        payload: Alert(" component=integrations.runner.Group integration_name=nri-sync
time="2020-09-16T18:13:56Z" level=debug msg="            AlertMessagePayload {" component=integrations.runner.Group integration_name=nri-sync
time="2020-09-16T18:13:56Z" level=debug msg="                level: Fatal," component=integrations.runner.Group integration_name=nri-sync
time="2020-09-16T18:13:56Z" level=debug msg="                description: AccessDenied," component=integrations.runner.Group integration_name=nri-sync
time="2020-09-16T18:13:56Z" level=debug msg="            }," component=integrations.runner.Group integration_name=nri-sync
time="2020-09-16T18:13:56Z" level=debug msg="        )," component=integrations.runner.Group integration_name=nri-sync
time="2020-09-16T18:13:56Z" level=debug msg="    }" component=integrations.runner.Group integration_name=nri-sync
time="2020-09-16T18:13:56Z" level=debug msg="thread 'main' panicked at 'nerdgraph request failed: hyper::Error(Connect, Custom { kind: Other, error: Custom { kind: InvalidData, error: AlertReceived(AccessDenied) } })', src/nrsync.rs:124:20" component=integrations.runner.Group integration_name=nri-sync
time="2020-09-16T18:13:56Z" level=debug msg="note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace" component=integrations.runner.Group integration_name=nri-sync
time="2020-09-16T18:13:56Z" level=debug msg="starting harvest" component=Plugins id=metadata/host_aliases
time="2020-09-16T18:13:56Z" level=debug msg="completed harvest, emitting" component=Plugins dataset="[{XXXXXXXXX hostname} {XXXXXXXXXX hostname_short}]" id=metadata/host_aliases
time="2020-09-16T18:13:56Z" level=debug msg="completed emitting" component=Plugins id=metadata/host_aliases
time="2020-09-16T18:13:56Z" level=debug msg="Updating identity" component=Agent new=XXXXXXXX old=XXXXXXXXX
time="2020-09-16T18:13:56Z" level=warning msg="integration exited with error state" component=integrations.runner.Group error="exit status 101" integration_name=nri-sync stderr="(last 10 lines out of 21):         version: TLSv1_0,\n        payload: Alert(\n            AlertMessagePayload {\n                level: Fatal,\n                description: AccessDenied,\n            },\n        ),\n    }\nthread 'main' panicked at 'nerdgraph request failed: hyper::Error(Connect, Custom { kind: Other, error: Custom { kind: InvalidData, error: AlertReceived(AccessDenied) } })', src/nrsync.rs:124:20\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace"
```

Could this be due to the agent trying to use TLS 1.0 for this communication?

**Comment by Kav91** [comment]
Hey @jrhinehart the way the agent communicates is independent to the integration communicating with nerdgraph so that should not be an issue.

Given the last section of this error:
```
payload: Alert(\n            AlertMessagePayload {\n                level: Fatal,\n                description: AccessDenied,\n            },\n        ),\n    }\nthread 'main' panicked at 'nerdgraph request failed: hyper::Error(Connect, Custom { kind: Other, error: Custom { kind: InvalidData, error: AlertReceived(AccessDenied) } })', src/nrsync.rs:124:20\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace"
```

This tells me that the nerdgraph request failed, and it sounds like an authenticate issue given the AccessDenied message. Are you able to confirm the package uuid and nerdgraph api key is correct? If you're still having trouble feel free to ping me internally the details you're using and I can take a closer look.

**Comment by Kav91** [comment]
closing due to inactivity
